name: My workflow

on: push

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to amazing-cord.surge.sh
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: 'amazing-cord.surge.sh'
          project: '.'
          login: ${{ secrets.surge_login }}
          token: ${{ secrets.surge_token }}
